### PR TITLE
Remove Sized for RngCore

### PR DESCRIPTION
**Pull request by kigawas**
Likewise https://github.com/zkcrypto/pairing/pull/108

### CODE REVIEW

**Comment by ibalajiarun** [comment]
Will this be merged soon?

**Comment by kigawas** [comment]
@ebfull Do you have time?

**Comment by str4d** [comment]
We will be merging this shortly as part of an update to our crate suite today.

**Comment by kigawas** [comment]
> We will be merging this shortly as part of an update to our crate suite today.

Can you merge the pr together?

**Comment by str4d** [comment]
The group crate has been updated with this fix. The PR should close once we push the updates to this repo, which will likely be later this week.

**Comment by str4d** [comment]
This was part of the group 0.6.0 release, the code for which has now been upstreamed here in #5.

**Pull request closed without merging**
